services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformQueryLanguage\API\Repository\EZQL:
        alias: EzSystems\EzPlatformQueryLanguage\Core\Repository\EZQL
        public: true

    EzSystems\EzPlatformQueryLanguage\Core\Repository\EZQL: ~

    EzSystems\EzPlatformQueryLanguage\Core\Repository\EZQL\EZQLProxyInterface:
        alias: EzSystems\EzPlatformQueryLanguage\Core\Repository\EZQL\EZQLProxy

    EzSystems\EzPlatformQueryLanguage\Core\Repository\EZQL\EZQLProxy:
        arguments:
            $criterionBindingsProviders: !tagged ezplatform.ezql.criterion_bindings_provider

    ### eZ Platform Integration

    EzSystems\EzPlatformQueryLanguage\Core\QueryType\EZQLQueryType:
        tags:
            - { name: ezpublish.query_type, alias: EZQL }
